version: '3.1'

services:

  mongo:
    image: docker.io/bitnami/mongodb:4.4
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes